version :"3"
services:
application:
image:BirthdayReminderApp
ports:
-"8080:8080"
networks:
- springboot-db-net
depends_on:
-mysqldb
volumes:
- /data/BirthdayReminderApp

mysqldb:
image: mysql:5.7
networks:
- springboot-db-net
environment:
- MYSQL_ROOT_PASSWORD=root
- MYSQL_DATABASE=sbms1
volumes:
- /data/mysql
networks:
 springboot-db-net:
