version: '3'

services:
     application:
        image: birthdayreminder
        ports:
          - 8080:80
        environment:
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
        depends_on:
         - mysqldb

     mysqldb:
         image: mysql:8.0.35
         ports:
            - 3306:3306
         environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: bdayreminder
            MYSQL_USER: root
            MYSQL_PASSWORD: root

